name: wasmgeoda build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, libgeoda ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    env:
      WASMGEODA_VER: '0.2.0'

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # with: emscripten-version: '1.38.47'
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10

      # Build wasmgeoda
      - name: Build wasmgeoda
        run: |
          rm libgeoda_src
          git clone --recursive https://github.com/geodacenter/libgeoda libgeoda_src
          ./build.sh
      
      # Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: jsgeoda.wasm-${{ env.WASMGEODA_VER }}
          path: |
            ${{ github.workspace }}/build/jsgeoda.wasm
            ${{ github.workspace }}/build/jsgeoda.js